export const INGREDIENTS_LOADING = 'INGREDIENTS_LOADING'
export const INGREDIENTS_SUCCESS = 'INGREDIENTS_SUCCESS'
export const INGREDIENTS_ERROR = 'INGREDIENTS_ERROR'
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS'