export const LOAD_INGREDIENTS_START: 'LOAD_INGREDIENTS_START' = 'LOAD_INGREDIENTS_START'
export const LOAD_INGREDIENTS_SUCCESS: 'LOAD_INGREDIENTS_SUCCESS' = 'LOAD_INGREDIENTS_SUCCESS'
export const LOAD_INGREDIENTS_ERROR: 'LOAD_INGREDIENTS_ERROR' = 'LOAD_INGREDIENTS_ERROR'
